FROM python:3.10
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY web/requirements . /code/web/requirements/

RUN apt update && apt install -y sqlite3 vim less
RUN pip3 install --upgrade pip
# RUN apt install libpq-dev
RUN pip3 install -r web/requirements/requirements_dev.txt
